### ISSUE TITLE
v-model data not part of OptionBuilder default value

### ISSUE THREAD

**Issue by ppounder** [laravel-enso/select#16]
Believe this might be a bug, or my implementation error

### Prerequisites
* [Y ] Are you running the latest version?
* [Y] Are you reporting to the correct repository?
* [Y] Did you check the documentation?
* [Y] Did you perform a cursory search?

### Description
First of all can I say, after struggling to implement the likes of Vue Multiselect with my Laravel Spark project this component is brilliant. Many thanks for taking the time to put this together. 

I have the component working as expected for a brand new form where I don't already have any persisted data. I just seem to be having a few issues with when I come to create the update form and data is already there and getting it to display the selected item pulled back from the DB.

### Steps to Reproduce
```
<vue-select 
    v-model="form.local_authority_id" //this is an ID of 2
    track-by="id"
    :options-limit=10
    label="name"
    source="/api/local_authorities">
</vue-select>
```

### Expected behavior
I would expect to see my first axios call to include the v-model data and therefore see:
```api/local_authorities?query=&value=2&optionsLimit=10```

This would then give me a query to my DB where it selects the first 10 from my table and whereIn('id = 2); so it brings back my actual record so it can display it.

### Actual behavior
The axios call is only:
```api/local_authorities?query=&value=&optionsLimit=10``` and it's missing 2 off the value. getParams() doesn't seem to hold 2 in this.value.

When I increase my optionsLimit up to say 200, which the DB then brings back the actual record, then it works but the query still is ```api/local_authorities?query=&value=&optionsLimit=10```. The hasSelection() method works here and selects the correct record as it's in the original DB call.

However when I use optionsLimit=10 my form.local_authority_id becomes null (checking it in Vue console tools). I'm assuming this is because it can't find the actual selected item so nulls it. It's a bit of a chicken and egg situation, because I need that value to send to the OptionsBuilder but it removes it.

I've tried console.logging ```this.value```, and it doesn't show anything in getParams(), however I can get it to output the correct value when looping in the hasSelection() method.

When I can get the value to be 2 in that axios call, it works perfectly. It just seems to lose my model data between adding it as a ```v-model```prop, to the first axios call to the DB.

Kind regards
Paul

**Comment by aocneanu** [comment]
Hi Paul,

Thank you for your appreciation :)

The `vue-select` markup seems right. `label` and `track-by` default to `name` / `id` so you can safely drop those 2 props.

Are you using the component in blade, or in another vue component?

The fact that `options-limit` does not take effect makes me believe that either the code is not compiled, or you are editing a different view, and this should be the problem for `v-model` as well.

Look in dev tools and see what prop does your `vue-select` component have for `options-limit`. Also see if it changes when you set it to a different value.

![image](https://user-images.githubusercontent.com/16073274/38492462-a49f6458-3bf7-11e8-84be-0d9291bc2d3f.png)

**Comment by ppounder** [comment]
Hi there,

```options-limit``` does take effect. It's just that if I make the limit bigger, it brings back all the records so the component does select the correct record because it's there in the original first query from the DB. So the hasSelection() method picks it up. It I decrease the options-limit down to say 10, the record isn't in the original query so hasSelection() can't pick it up. Just not sure why or where it seems to lose the form.local_authority_id in this.value.

It does get called from another component. I'm using Laravel Spark so it is being called from there. However Spark uses inline component, so I'm actually calling the VueSelect from within a blade template within the Spark inline component.

![screen shot 2018-04-09 at 11 32 55](https://user-images.githubusercontent.com/343006/38493391-f5fdbd12-3be9-11e8-86f9-bdba54dbe7f6.png)

![screen shot 2018-04-09 at 11 32 35](https://user-images.githubusercontent.com/343006/38493403-fc68be36-3be9-11e8-9872-5efd93fd2b4a.png)

If I was to remove the VueSelect, the local_authority_id becomes 2 in the Vue console tools.

**Comment by aocneanu** [comment]
>options-limit does take effect. 

>When I increase my optionsLimit up to say **200**, which the DB then brings back the actual record, then it works but the query still is api/local_authorities?query=&value=&optionsLimit=**10**.

ah ok, the above got me confused from the first post, I thought it does not take effect.

Moving on, the `form` object has properties and values (`form.local_authority_id`) when the `vue-select` component is rendered?

If you're not sure you can put a `v-if="form.local_authority_id"` on the `vue-select` just for testing purpose.

**Comment by ppounder** [comment]
I believe it does, but I’ll confirm this is the case later. Just out at the moment.

**Comment by ppounder** [comment]
Ok, well that kind of fixed it :-) I can't explain this at all. 

I've added the ```v-if="form.local_authority_id"``` on the vue-select to check that the component is visible. It is visible, and now I can see the prop values in there.

Take the ```v-if``` out, and they disappear :-) Screenshots showing the Vue tools with the ```v-if``` in. I've not used Vue much yet myself, so can't really explain it. Glad it's working, but not sure why adding some conditional code into the component can force it to work. 

Appreciate this might just be happening with mine and it's not actually a bug itself with the component.

![screen shot 2018-04-09 at 15 04 18](https://user-images.githubusercontent.com/343006/38502644-dd16ebac-3c07-11e8-8628-71f343dc4e08.png)

![screen shot 2018-04-09 at 15 04 26](https://user-images.githubusercontent.com/343006/38502660-e3b6a5ba-3c07-11e8-8c90-93e2107978dc.png)

**Comment by aocneanu** [comment]
Actually it looks like you have race condition. Do you mind posting the full code for this view?

**Comment by ppounder** [comment]
Ahh, that would actually make a bit more sense. Code is below, I've simplified this a lot, but what is probably happening here is that the VueSelect is rendering before I've retrieved back the information from the parent component.

Here is the js for the establishement-edit-form inline component:

```
Vue.component('establishment-edit-form', {
    props: ['user', 'establishmentId'],

    data() {
        return {
            establishment: [],
            form: new SparkForm({
                local_authority_id: '',
            })
        };
    },

    mounted() {
        
        this.getEstablishment();

    },
    
    methods: {
        getEstablishment() {
            axios.get('/api/establishments/' + this.establishmentId)
                .then(response => {
                    this.establishment = response.data;
                    this.populateForm();
                });
        },

        update() {

            Spark.put('/api/establishments/' + this.establishmentId, this.form)
                .then(response => {
                    console.log(response);
                });
        },

        populateForm() {
            this.form.local_authority_id = this.establishment.local_authority_id;
        }
    }
    
});
```

Here is the blade template with the inline component added. I've removed a lot of the other form data for brevity:
```
<establishment-edit-form :user="user" :establishment-id="{{ $establishment }}" inline-template>

    <form role="form">

        <div class="form-group">
            <label class="control-label">Local Authority</label>

            <vue-select 
                v-if="form.local_authority_id"
                v-model="form.local_authority_id"
                :options-limit=10
                source="/api/local_authorities">
            </vue-select>

            <span class="invalid-feedback" v-show="form.errors.has('local_authority_id')">
                @{{ form.errors.get('local_authority_id') }}
            </span>
        </div>

        <div class="form-actions pull-right">

            {!! csrf_field() !!}

            <button class="btn btn-primary" @click.prevent="update" :disabled="form.busy">

                <span v-if="form.busy">
                    <i class="fa fa-btn fa-spinner fa-spin"></i> {{__('Editing')}}
                </span>

                <span v-else>
                    <i class="fa fa-btn fa-check-circle"></i> {{__('Edit')}}
                </span>

            </button>

        </div>

    </form>

</establishment-edit-form>
```

If this is the case, how can I prevent the VueSelect component from rendering until I've got the data back in the parent component (from the this.getEstablishment()) method call. This populates the form, which is then used in the Select component?

I appreciate now this isn't a bug, but more around how I've implemented the component. So I do thank you for your help. Happy for this to be closed, I can do some investigating.

Regards
Paul

**Comment by aocneanu** [comment]
So this was it.

I tried to clean things up a little, hope that it does not break something else:

```
Vue.component('establishment-edit-form', {
    props: ['user', 'establishmentId'],

    data() {
        return {
            form: null
        };
    },

    created() {   
        this.getForm();
    },
    
    methods: {
        getForm() {
            axios.get(`/api/establishments/${this.establishmentId}`)
                .then(({ data }) => {
                      this.form = new SparkForm(data)
                 });
        },

        update() {
            Spark.put(`/api/establishments/${this.establishmentId}`, this.form)
                .then(response => {
                    console.log(response);
                });
        },
    }
});
```

and in the template

```
<establishment-edit-form :user="user" :establishment-id="{{ $establishment }}" inline-template>

    <form role="form"
          v-if="form">
        <div class="form-group">
            <label class="control-label">Local Authority</label>

            <vue-select v-model="form.local_authority_id"
                :options-limit="10"
                source="/api/local_authorities">
            </vue-select>

            <span class="invalid-feedback" v-show="form.errors.has('local_authority_id')">
                @{{ form.errors.get('local_authority_id') }}
            </span>
        </div>

        <div class="form-actions pull-right">

            {!! csrf_field() !!}

            <button class="btn btn-primary" @click.prevent="update" :disabled="form.busy">

                <span v-if="form.busy">
                    <i class="fa fa-btn fa-spinner fa-spin"></i> {{__('Editing')}}
                </span>

                <span v-else>
                    <i class="fa fa-btn fa-check-circle"></i> {{__('Edit')}}
                </span>

            </button>

        </div>
    </form>

</establishment-edit-form>

```

I don't think that you want the form rendered without having its data first.

**Comment by ppounder** [comment]
Perfect, many thanks.

Thanks again for your help today, appreciate this ended up being my implementation not your component. Good luck with [laravel-enso.com ](laravel-enso.com )

**Comment by aocneanu** [comment]
If you like the package please give it a star.

Thank you too!

**Comment by ppounder** [comment]
Of course, done 👍
