### ISSUE TITLE
VueSelect coudn't show multiple column value as label

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/select#17]
This is  a **feature request**.

1. First Step
2. Second Step
3. and so on...
-->

I need server side select component label contain multiple column value. such as code with name

### Expected behavior

show multiple column value
### Actual behavior

:label attribute get only 1 column name

**Comment by aocneanu** [comment]
You can already achieve this.

When you use the vue select in server side mode, what you get in the FE as `optionList` is an array of objects from the query result on the main model.

For instance, in you look at how we handle the owner [roles](https://github.com/laravel-enso/RoleManager/blob/master/src/app/Http/Controllers/RoleSelectController.php) with serverside, this controller is returning an array of objects of the following form:

![image](https://user-images.githubusercontent.com/16073274/39751383-b0a8ee60-52c0-11e8-9546-aa28c2b9e550.png)

This means that you can easily compute your label by adding an accessor to the model, let's say `getLabelAttribute`, and then set `protected $appends = ['label']`, and after, in the FE just set the [`label`](https://github.com/laravel-enso/Select/blob/master/src/resources/assets/js/components/enso/select/VueSelect.vue#L119) prop of the VueSelect `label="label"`.

**Comment by shonhor22** [comment]
thank you it works
