### ISSUE TITLE
Master/Slave Select

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/select#20]
Could you provide an example of how the master/slave selects work on here?
https://www.laravel-enso.com/examples/select

I am currently implementing such a feature and would appreciate if I could check the "correct" way of doing this.

**Comment by aocneanu** [comment]
in user's edit [form] (https://github.com/laravel-enso/Enso/blob/master/resources/assets/js/pages/administration/users/Edit.vue)

the [select demo](https://github.com/laravel-enso/Enso/blob/master/resources/views/examples/select/index.blade.php)

You can paste here your code and maybe I can help.

**Comment by stevefrost** [comment]
I've got it working, the first select has a source, and on the @input event I trigger a method to update the options of the second select.

**Comment by aocneanu** [comment]
Perfect :) Can we close this?

**Comment by MonteiroCM** [comment]
I use im FormBuilder, can i make the template to do this ?
