### ISSUE TITLE
Removing a tag doesn't emit an 'input' event

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/select#21]
This is  a **bug?**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
When you choose an option on the dropdown it emits an input event, when you click clear it emits an input event, but when you remove a tag it doesn't emit an input event.

### Steps to Reproduce
Remove a tag from the dropdown

### Expected behavior
an input event should be emitted

### Actual behavior
no event is emitted

**Comment by aocneanu** [comment]
sortable
![image](https://user-images.githubusercontent.com/16073274/42996063-22329f66-8c1b-11e8-9bb1-b53153c56912.png)

**Comment by aocneanu** [comment]
https://github.com/laravel-enso/Select/blob/master/src/resources/assets/js/components/enso/select/Tag.vue#L7

**Comment by stevefrost** [comment]
The remove event doesn't bubble up to the vue-select-filter component though, the input does.

**Comment by aocneanu** [comment]
Yeah, the input needs to bubble up for the v-model to work. But I got the point :)
