### ISSUE TITLE
Is it possible to send the focus to the component?

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/select#28]
### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

I would like to know if it is possible to send the focus to the component in any way?
I have tried a thousand ways but it has not been possible for me :(
Thank you in advance, thank you again, I have brought a lot of personal fruit to all Enso

**Comment by aocneanu** [comment]
>I would like to know if it is possible to send the focus to the component in any way?

Please provide more details about what you are trying to achieve.

**Comment by heyner29** [comment]
I have an input text that when pressing Enter it does a couple of processes in the backend, depending on the result it should go to a vue-select X or a vue-select And within the same form I would like to be able to send the focus to the vue-select automatically and not that you have to scroll with the mouse and click.
Another case is that I have a vue-select to filter products, I already achieved that by pressing Enter and selecting an option, go to an input quantity, in this input, pressing Enter adds these two data to an array and I would like them to be positioned after them again in the vue-select.
I do not know if I was clear in the use cases :(

**Comment by aocneanu** [comment]
`this.$refs.select.$el.querySelector('fieldset').click()`

**Comment by heyner29** [comment]
Thank you very much, it's just what I needed.

**Comment by heyner29** [comment]
> `this.$refs.select.$el.querySelector('fieldset').click()`

Hello, this served me at that time, but now with the new version it seems not to work :( You could guide me as I could get the same result with the new component.

**Comment by aocneanu** [comment]
Sure, replace `fieldset` with `.button`

**Comment by heyner29** [comment]
I had already tried that option and returns the focus but it closes :(
I will attach a couple of demonstrations of how it worked before and now.
### Before
![before](https://user-images.githubusercontent.com/12703614/58061887-b61baf80-7b3d-11e9-9c64-6022099820eb.gif)
### Now 
I hope you can notice that it closes at the moment

![now](https://user-images.githubusercontent.com/12703614/58061917-d0558d80-7b3d-11e9-9631-c02c81d69ad3.gif)
Before I used `VueSelect`. Now I'm using `EnsoSelect`

**Comment by aocneanu** [comment]
share the code behind this, maybe I can spot something.

**Comment by heyner29** [comment]
In a method that adds the selected product to an array and then empties the fields and should reposition itself in the select.
![carbon](https://user-images.githubusercontent.com/12703614/58097597-6b318480-7b9d-11e9-9d27-453ad07124b7.png)
And I use it in the `@click` event of the Add button and in the `KeyPress:Enter` of Qty

**Comment by aocneanu** [comment]
try `@click.stop="addproduct"` on the add button. [docs](https://vuejs.org/v2/guide/events.html#Event-Modifiers)

**Comment by heyner29** [comment]
> try `@click.stop="addproduct"` on the add button. [docs](https://vuejs.org/v2/guide/events.html#Event-Modifiers)

Yes, thank you very much. This solution worked for me.
