### ISSUE TITLE
Error in render: "TypeError: Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by MonteiroCM** [laravel-enso/select#29]
This is  a **bug | feature request**.

### Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
* [ x] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description

I create a Templates Form in Enso Laravel

```
{
    "routePrefix": "financeiro.lancamentos",
    "sections": [{
        "columns": 2,
        "fields": [{
            "label": "Categoria",
            "name": "categoria_id",
            "value": null,
            "meta": {
                "type": "select",
                "multiple": false,
                "source": "financeiro.categorias.options",
                "options": []
            }
        }]
    }]
}

```

And I try to change for column seach.

```
<?php

namespace App\Http\Controllers\Financeiro\Categorias;

use App\Categoria;
use App\Http\Controllers\Controller;
use LaravelEnso\Select\app\Traits\OptionsBuilder;

class CategoriaSelectController extends Controller
{
    use OptionsBuilder;

    protected $model = Categoria::class;

    protected $queryAttributes = ['nome'];
}
```

but I can´t do that..

**Comment by MonteiroCM** [comment]
![erro](https://user-images.githubusercontent.com/2496628/51445776-17e31e80-1cf0-11e9-8708-5d0d9438abd9.png)

**Comment by aocneanu** [comment]
The select package, as pointed in the docs, assumes the existence of `name` and `id` in the primary model's table. From what I'm seeing you are using `nome`, so you need to customize the `label` option / prop to `nome`.

So in the json template's meta add `"label": "nome"`.

**Comment by MonteiroCM** [comment]
thank you, but i don't find this in docs, but your help me with this , if you have the link of the part of the docs explain other functions of template

**Comment by aocneanu** [comment]
sure, [docs](https://docs.laravel-enso.com/packages/select.html#usage)
