### ISSUE TITLE
Master/Slave using  

### ISSUE THREAD

**Issue by soumilgada** [laravel-enso/select#30]
This is  a feature request.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
How can we have master slave select using Form Builder JSON.
Also can we have params added to source inside meta attribute.

**Comment by aocneanu** [comment]
>How can we have master slave select using Form Builder JSON.

[demo](https://www.laravel-enso.com/examples/select)
[code](https://github.com/laravel-enso/Examples/blob/master/src/resources/views/select/index.blade.php)

>Also can we have params added to source inside meta attribute.

no, but [you can use the `append()` helper](https://docs.laravel-enso.com/packages/form-builder.html#advanced-usage)

**Comment by soumilgada** [comment]
Thank you for prompt response.
I have two selects based on first input I want to fetch second select's options.
My entire form is being built using Json file Builder.

**Comment by aocneanu** [comment]
you will have to use "meta: {custom:true}" in order to chain them.


[view](https://github.com/laravel-enso/Core/blob/master/src/resources/customizableJs/pages/administration/users/Edit.vue)

[template](https://github.com/laravel-enso/Core/blob/master/src/app/Forms/Templates/user.json)

This would have been really easy for you to find by yourself ;)

**Comment by soumilgada** [comment]
I tried the above mentioned approach
`{
                "label": "Type",
                "name": "complainType",
                "value": null,
                "meta": {
                    "custom": true,
                    "type": "select",
                    "multiple": false,
                    "options": "App\\Enums\\Complain"
                }
            },{
                "label":"Complain Reason",
                "name":"complainReason",
                "value":null,
                "meta": {
                    "custom": true,
                    "type": "select",
                    "options": [ ]
                }
            }
`

And 
`<template slot="complainType"
                          slot-scope="{ field, errors, i18n }">
                    <select-field :errors="errors"
                                  :field="field"
                                  :i18n="i18n"
                                  @input="complainType = $event"/>
                </template>`
2
`
                <template slot="complainReason"
                          slot-scope="{ field, errors, i18n }">
                    <select-field :errors="errors"
                                  :field="field"
                                  :i18n="i18n"
                                  :pivot-params="pivotParams"/>
                </template>`

My Data Init is 
`pivotParams: { complain: { type: null } },`

For some reason it is not working

**Comment by aocneanu** [comment]
read more carefully the examples I gave you. For sure you are missing something.
>Did you check the documentation?
And read the docs.

**Comment by soumilgada** [comment]
Thanks for the solution, now list populates. But my concern now it doesnt get added to Form data
