### ISSUE TITLE
Use the vue component Independently

### ISSUE THREAD

**Issue by omdesignz** [laravel-enso/select#34]
Hi there,
Is it possible to use this component independently?
I cant seem to find any awesome select component which supports bulma css.

This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by aocneanu** [comment]
Yes. You can use the only the FE, or the FE with BE on Laravel.

check the [demo](https://www.laravel-enso.com/examples/select) and the [actual implementation](https://github.com/laravel-enso/Examples/blob/master/src/resources/views/select/index.blade.php)
