### ISSUE TITLE
trackBy parameter doesn't seems to work on edit form

### ISSUE THREAD

**Issue by lsosa3** [laravel-enso/select#37]
This is  a **bug | feature request**.

### Prerequisites
* [y ] Are you running the latest version?
* [y ] Are you reporting to the correct repository?
* [y] Did you check the documentation?
* [y ] Did you perform a cursory search?

### Description

Hi guys, i build a crud using the structure-manager, it has several select fields. The create form works great but the edit form doesn't get the selected values in the selects fields that refer to other model. 
I review a lot the code and compare with many of the vendor laravel-enso code but i can't see what i am missing.
Help please

Thanks in advance
### Steps to Reproduce

Run structure-manager
...
Add necesary data to the json files 

### Expected behavior

Show the selected values in the create form selects 
### Actual behavior

Doesn't get the selected values in the selects fields that refer to other model.
I used the trackBy and label parameters and again it works fine in the create form but in the edit form don't

![Selección_011](https://user-images.githubusercontent.com/14814335/54067527-65bbd380-4217-11e9-8956-0d89a77ecd0f.png)

![Selección_007](https://user-images.githubusercontent.com/14814335/54067458-9d764b80-4216-11e9-8c7e-5d07ba7a28b9.png)
![Selección_008](https://user-images.githubusercontent.com/14814335/54067467-baab1a00-4216-11e9-983e-664dbbc60314.png)
![Selección_009](https://user-images.githubusercontent.com/14814335/54067474-d9111580-4216-11e9-9ba8-9a49a17768dc.png)
![Selección_010](https://user-images.githubusercontent.com/14814335/54067485-f3e38a00-4216-11e9-984f-4d950f41f1c0.png)
![Selección_012](https://user-images.githubusercontent.com/14814335/54067560-ca772e00-4217-11e9-96a8-111c71d54555.png)
![Selección_013](https://user-images.githubusercontent.com/14814335/54067568-dcf16780-4217-11e9-8f2e-3118ef4ced50.png)

**Comment by aocneanu** [comment]
You're [missing](https://github.com/laravel-enso/Select/blob/master/src/app/Traits/OptionsBuilder.php#L16) the `public $trackBy = 'id_nacionalidad` property in your SelectController

I think that we can improve this in the future by reusing the prop used in the FE component ((adding it to the request).

**Comment by lsosa3** [comment]
Thank you that was it.
Now it works perfectly
