### ISSUE TITLE
Custom queryAttribute - missing options labels

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/select#40]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Problem: 
Select options are missing names(labels). 
I'm trying to create a simple form where 1-n relations are set.
I have a "Group" model, where a FK "permission_group_id" can be set.
For this I tried using a select field with the options from the "PermissionGroup" controller

/app/Http/Controllers/Models/Permissiongroups/Options.php
`
class Options extends Controller
{
    use OptionsBuilder;

    protected $model = PermissionGroup::class;

    protected $queryAttributes = ['permission_group_name'];

    public function query(Request $request)
    {
        return PermissionGroup::query();
    }
}
`
/app/Forms/Templates/Models/group.json
`
{
  "routePrefix": "models.groups",
  "sections": [
    {
      "columns": 2,
      "fields": [
        {
          "label": "Permission Group Id",
          "name": "permission_group_id",
          "value": null,
          "meta": {
            "type": "select",
            "multiple": false,
            "options": [],
            "source": "models.permissiongroups.options"
          }
        },
        {
          "label": "Group Name",
          "name": "group_name",
          "value": null,
          "meta": {
            "custom": false,
            "type": "input",
            "content": "text",
            "disabled": false
          }
        }
      ]
    }
  ]
}
`

/app/Tables/Builders/Models/GroupTable.php
`
class GroupTable extends Table
{
    protected $templatePath = __DIR__.'/../../Templates/Models/groups.json';

    public function query()
    {
        return Group::selectRaw('
            groups.id as "dtRowId",
            groups.permission_group_id as "dtRowPermissionGroupId",
            groups.group_name as "dtRowGroupName"
        ');
    }
}
`

I think the problem is the deviation from the default "name" queryAttribute which is expected, and in my situation the "name" which should be used as select option label is called "permission_group_name"

Ajax call is returning a valid JSON ;
![image](https://user-images.githubusercontent.com/16973022/61559119-9804f980-aa71-11e9-830f-60c6113b06c1.png)

### Steps to Reproduce
Create a Select field which uses the options of a different model which has no "name" column.

### Expected behavior
To see the options generated in the options

### Actual behavior
Options are generated but without a name
![image](https://user-images.githubusercontent.com/16973022/61558422-a3572580-aa6f-11e9-8dc6-f579e9351ad0.png)

**Comment by aocneanu** [comment]
[docs](https://docs.laravel-enso.com/frontend/select.html#usage)

>label - string, optional, default name - the attribute that is to be used as label from the result/options list

the front end component needs this attribute. If you're using `enso-form` / `vue-form` you should add  `"label": "permission_group_name"` to the field's `meta` object

**Comment by robbykrlos** [comment]
> [docs](https://docs.laravel-enso.com/frontend/select.html#usage)
> 
> > label - string, optional, default name - the attribute that is to be used as label from the result/options list
> 
> the front end component needs this attribute. If you're using `enso-form` / `vue-form` you should add `"label": "permission_group_name"` to the field's `meta` object

Nice! Thank you. I'm still getting familiar with enso, had thought that the select documentation should have contained this detail, although makes perfect sense to be a front-end thing... duuh..

Now I know! Have a good weekend.

**Comment by aocneanu** [comment]
The link **is** from the select documentation, but the FE part :)

**Comment by robbykrlos** [comment]
> The link **is** from the select documentation, but the FE part :)

<*synapses firing*>
