### ISSUE TITLE
keep select in disabled state

### ISSUE THREAD

**Issue by jaminjava** [laravel-enso/select#43]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description
How to keep select list in disabled state until its loading the  options from source??? so tht users cant click on select list till its loading options

**Comment by aocneanu** [comment]
You mean for the first fetch or after?

The component should have this behavior by default.

**Comment by jaminjava** [comment]
in parent child relation, when I select parent select list, it loads the child select list, so while loading the child select list should be disabled so that user cant click on it while its loading. And it doesn't have this behavior by default.
one question is that how can I disable change feature in form? I mean when we submit form or edit it, it keeps the data which is written in it. I want to disable this feature for whole project. How can I do this?

**Comment by aocneanu** [comment]
please open 1 issue / 1 topic

**Comment by jaminjava** [comment]
ok sorry kindly just tell this on: 
in parent child relation, when I select parent select list, it loads the child select list, so while loading the child select list should be disabled so that user cant click on it while its loading. And it doesn't have this behavior by default.

**Comment by aocneanu** [comment]
@jaminjava it was fixed with the commit above (run yarn upgrade && yarn)

**Comment by aocneanu** [comment]
The previous attempt at this was not the good solution so I had to reevaluate.

In the latest version I've updated the strategy for disabling selection while params are changing / list is fetching
