### ISSUE TITLE
Options ordering - more sorting flexibility.

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/select#46]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Hi,

I want to suggest an improvement on the LaravelEnso\Select\Services\Options. I can help with a contribution in this direction, only if you are accepting it.

Here's the problem - Select options used everywhere (filters, forms) are sorted CASE-SENSITIVE:
```
Alix
Beatrice
Zorro
adam
bill
```

I need this to be case-Insensitive.

like:

```
adam
Alix
Beatrice
bill
Zorro
```

I've tracked down the BE code "at fault" and it seems that inside 
vendor/laravel-enso/select/src/Services/Options.php
```php
private function get(): Collection
    {
        return $this->query->whereNotIn($this->trackBy, $this->value)->get()
            ->toBase()
            ->merge($this->selected)
            ->when($this->orderBy !== null, fn ($results) => $results->sortBy($this->orderBy))
            ->values()
            ->when($this->appends, fn ($results) => $results->each->setAppends($this->appends));
    }
```
the end results are finally sorted as a Collection using sortBy with default sort flag SORT_REGULAR.

vendor/laravel/framework/src/Illuminate/Collections/Collection.php
```
public function sortBy($callback, $options = SORT_REGULAR, $descending = false)
```

And since is was implemented by you in this way I guess there is a reason behind it.

### My suggestion

Extend the select configuration with extra config:
vendor/laravel-enso/select/config/select.php
```
/*
    |--------------------------------------------------------------------------
    | Sort By Flags
    |--------------------------------------------------------------------------
    | The sort by flags used for every select. 
    | Possible flag are SORT_REGULAR, SORT_NUMERIC, SORT_STRING, SORT_NATURAL, SORT_FLAG_CASE...
    | @link https://php.net/manual/en/array.constants.php
    */

    'sortByFlags' => SORT_REGULAR,
```

and use this inside the private method 
vendor/laravel-enso/select/src/Services/Options.php
```php
private function get(): Collection
    {
        return $this->query->whereNotIn($this->trackBy, $this->value)->get()
            ->toBase()
            ->merge($this->selected)
            //HERE ->>>>>>>>>>>>>
            ->when($this->orderBy !== null, 
                fn ($results) => $results->sortBy($this->orderBy, Config::get('enso.select.sortByFlags')))
            ->values()
            ->when($this->appends, fn ($results) => $results->each->setAppends($this->appends));
    }
```

So that other Enso users can change this easily.

I would have done this locally but customizing the private method with bindings means I need to "copy" the whole class and I don't like that.

Let me know if you think it's a good idea, and if you would accept such MR.

**Comment by robbykrlos** [comment]
LE: I just realized that I can't even use bindings, since in vendor/laravel-enso/select/src/Traits/OptionsBuilder.php, Options is instantiated with "new" :
```php
private function response(Request $request)
{
...
     return (new Options($query))
```

So I know you guys are busy with PHP 8.0 upgrade, but in the future any flexibility in this direction would be appreciated.

Thank you!

**Comment by aocneanu** [comment]
I guess this would be a good addition. Please make a PR.

Thank you.

**Comment by aocneanu** [comment]
And let’s call the option ‘ sortByOptions’ to be consistent woth the framework.

**Comment by robbykrlos** [comment]
Will proceed tomorrow Friday ~afternoon. Thanks for the green light.

**Comment by robbykrlos** [comment]
Hi,

just made the PR : PR for Options ordering - more sorting flexibility. #46 #47

About the "continuous-integration/styleci/pr — Issues have been identified with 2 files" - I see no issues with my change. Don't know why the styleci fails.

**Comment by robbykrlos** [comment]
@aocneanu shouldn't this change be documented in the Upgrade steps of 4.8.1 ? 

config should be synced with parent one?

`'sortByFlags' => SORT_REGULAR,`

Just asking...

And btw, some #XX links from the release notes are pointing to wrong projects. (even this #46, is pointing to enso project instead of select)

**Comment by aocneanu** [comment]
@GITmanuela please take care of documenting this in the latest release / upgrade steps and after close this issue

**Comment by aocneanu** [comment]
@GITmanuela, was this done?

**Comment by GITmanuela** [comment]
Yes. We've updated the 4.8.1 release notes and we'll also include a mention in the latest release as a upgrade step.
