### ISSUE TITLE
Set label name

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/select#8]
I have defined the following vue-select-filter:

```
<vue-select-filter
            :title="filterTitle"
            :value="value"
            label="output_name"
            :options="filterOptions"
           @input="update">
    </vue-select-filter>
```

My options look like the following:
```
[
    {
        "output_name": "xxx",
        "id": 1
    },
    {
        "output_name": "yyy",
        "id": 2
    },
...
```

But I get the following error and no options are displayed:
![screenshot 2018-03-09 18 01 59](https://user-images.githubusercontent.com/7204559/37219529-0520cd18-23c4-11e8-9e6e-a9a259dd9671.png)

Is there something different since refactoring vue-select?

And is the server side component in use anywhere?

**Comment by mauthi** [comment]
with server side vue-select label name is working - but not with client side

**Comment by aocneanu** [comment]
VueSelect expects an array of objects with `id` and `label` as properties. But you can customize this using the `trackBy` and `label` props.
